title: Ubaldo Hervás
description: Experimentación Online
url: "https://ubaldohervas.github.io"
baseurl: "/experimentacion-online-codigos"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
